export * from "./Hero";
export * from "./Calculator";
export * from "./Result";
export * from "./SalesPage";
export * from "./ThankYou";
export * from "./Interpretations";
export * from "./TermsPrivacy";
export * from "./DesignShowcase";
export * from "./PageWrapper";
